const anh_sp = [
    { id: '1', source: require('../../assets/image/sung-massage-vispo-vp-s21-den.jpg')},
    { id: '2', source: require('../../assets/image/may-massage-cam-tay-thong-minh-life360-ms-al21-3.jpg')},
    { id: '3', source: require('../../assets/image/may-massage-xung-dien-hv-f128.jpg')},
    { id: '4', source: require('../../assets/image/bon-massage-chan-beurer-fb-50.png')},
    { id: '5', source: require('../../assets/image/may-do-huyet-ap-co-tay-beurer-bc30.jpg')},
    { id: '6', source: require('../../assets/image/may-do-huyet-ap-bap-tay-omron-hem-7156-14.jpg')},
    { id: '7', source: require('../../assets/image/may-do-huyet-ap-co-microlife-ag1-20-63d8db9d4930c.jpg')},
    { id: '8', source: require('../../assets/image/YEA650D.png')},
    { id: '9', source: require('../../assets/image/may-do-duong-huyet-microlife-diarite-bgm.jpg')},
    { id: '10', source: require('../../assets/image/may-do-duong-huyet-yuwell-accusure-710-1.jpg')},
    { id: '11', source: require('../../assets/image/may-do-duong-huyet-beurer-gl42.jpg')},
    { id: '12', source: require('../../assets/image/may-do-duong-huyet-cao-cap-yuwell-582-3.jpg')},
    { id: '13', source: require('../../assets/image/can-suc-khoe-dien-tu-laica-ps-3005-a.jpg')},
    { id: '14', source: require('../../assets/image/can-suc-khoe-life360-ar-s17f-1.jpg')},
    { id: '15', source: require('../../assets/image/can-co-hoc-beurer-ms01.jpg')},
    { id: '16', source: require('../../assets/image/can-do-luong-mo-co-the-omron-hbf-224-sl1.jpg')},
    { id: '17', source: require('../../assets/image/mang-che-mat-choi-golf-chong-tia-uv-koz004-1.jpg')},
    { id: '18', source: require('../../assets/image/mang-che-mat-choi-golf-chong-tia-uv-koz004-1.jpg')},
    { id: '19', source: require('../../assets/image/00029787_khau_trang_hamita_n95_hop_10_cai_9943_6058_large_e0f0918587.webp')},
    { id: '20', source: require('../../assets/image/00029785_khau_trang_hamita_tre_em_meo_kitty_hop_50_cai_2955_62ae_large_1af149a8ca.webp')},
    { id: '21', source: require('../../assets/image/may-tao-oxy-5-lit-yuwell-7f-5cw-mini-2.jpg')},
    { id: '22', source: require('../../assets/image/may-tao-oxy-oxygen-concentrator-imedicare-ioc-03n.jpg')},
    { id: '23', source: require('../../assets/image/may-tao-oxy-gia-dinh-yu300.jpg')},
    { id: '24', source: require('../../assets/image/may-tao-oxy-imedicare-ioc-5ls-5-lit-s5.jpg')},
    { id: '25', source: require('../../assets/image/nhiet-ke-dien-tu-hong-ngoai-yuwell-yt-1c.jpg')},
    { id: '26', source: require('../../assets/image/nhiet-ke-dien-tu-omron-mc-246.jpg')},
    { id: '27', source: require('../../assets/image/nhietkebeurer-ft58.jpg')},
    { id: '28', source: require('../../assets/image/tuJpHq7stcR8.jpg')},
];

export default anh_sp;
